# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

// set default tuquito.org.ar
user_pref("browser.startup.homepage", "file:///usr/share/tuquito/inicio/index.html");

// sonido al finalizar descarga
pref("downbar.function.soundOnComplete", 1);
